#! /bin/bash
# Wrapper script to shorten speaking time for festival text to speech

startVol=`aumix -q | grep vol | sed 's/vol.[0-9]*\,\ //'`

aumix -v 100
echo "$@" | festival --tts
aumix -v $startVol
